### PR TITLE
quick fix for generation

### PR DESCRIPTION
**Pull request by tartavull**
Working in progress and dirty fix in case you find it useful

---
This change is [Reviewable](https://reviewable.io/reviews/janelia-flyem/dvid/195)

### CODE REVIEW

**Comment by DocSavage** [comment]
Hi, Ignacio, could you describe a bit more about the size of the volume and how large of an image you're trying to pull from dvid?  From the past debug info you gave, it sounds like your image volume is `73219 x 40974 x 1274`.  In your pull request, you are disabling the max data size limits, which are already significantly higher than Google has allowed with their brain maps API.  Main issue here is possible timeouts by the HTTP client unless you disable it. 

I can't except pull as is because of the hardwired "false" to circumvent the data size return limits.  I'll think about the proper way to handle really large requests, which includes a look at other protocols if HTTP isn't best way to send this amount of data (vs grpc for example).

**Comment by tartavull** [comment]
HI Bill,
  That's correct, grasycale's max point is [73219,40974,1274].
  When running generate on image tiles it tries to do a request of 17gb while the limit is 3gb.
  I wasn't sure why such a large request is made, it seems to me that it is not necessary for doing  downsampling with a tile size of 512x512.
  I've created the PR to inform of where the problem was, no need to merge this.

**Comment by DocSavage** [comment]
The tile generation code was written assuming a different max size for volume and was optimized for simplicity and speed.  Since grayscale is usually 32^3 voxel blocks, it allocates a "slab" of NX x NY x 32 voxels and works on tile generation for the entire slab, where NX and NY are the max X and Y of the volume.  This fails if NX and NY grows too large, but makes things simple since the full extent high-res XY is available and can be downsampled and tiles extracted level-by-level with a single store per tile (and no tile reads).

I'd be more than happy to receive a better tile generation algorithm for larger volumes, even if it requires storing tiles at higher-res then retrieving those tiles again during the tile generation process.  This would remove the larger memory buffer requirement at the cost of some additional reads from disk.

**Comment by DocSavage** [comment]
I made explicit how [we'd generate tiles for small vs large volumes](https://github.com/janelia-flyem/dvid/wiki/Tile-Generation#generating-the-tiles-large-dataset).  

Currently, DVID doesn't distinguish datatypes based on whether we know their key space (and can generate keys from key A -> key B) or not.  For datatypes like imageblk and labelblk, we use a defined ZYX key so given two block coordinates, we can generate all keys between them without invoking a range query.  This could improve performance for immutable instances, so we should bake it into the storage package.

**Pull request closed without merging**
