### PR TITLE
conda recipe

### PR DESCRIPTION
**Pull request by stuarteberg**
This PR adds a conda recipe for building DVID, with the goal of making DVID's BuildEM requirement obsolete.  I need a little help finishing it; here are some notes:

1. C Dependencies such as `basholeveldb` are acquired via conda, not BuildEM.

2. Go dependencies are fetched during the build.  That is, all `go get` commands are run every time the recipe is built, but those commands run fairly quickly.  I listed each of the `go get` source repos in the `meta.yaml`, so `conda-build` will clone them into the build environment's `GOPATH` before the build script even starts.  Therefore, `go get` has very little work to do -- it may be unnecessary.  (BTW, `conda-build` is able to clone them into place quickly because it maintains a local cache of all source repos.)

3.  ~There is currently no flexibility w.r.t. build target selection.  The recipe as currently written always builds all binaries, and hard-codes the backend choice(s).~

    a. **Edit:** I should also mention that the list of dependencies should be shortened.  Instead of closely examining the old `CMakelists.txt` file to determine which specific dependencies are needed to support the leveldb/gbucket backends, I just added every single dependency even mentioned in the original `CMakelists.txt`.  Surely some of them ought to be discarded.

4. ~The tests will be run as part of the build unless you define `DVID_SKIP_TESTS` in your environment prior to running `conda-build`.  Currently, not all tests are passing in this setup, so I need some help.~ **Edit:** The new `Makefile` has a `test` target, but it doesn't work yet.  Need help.

5. ~This recipe is designed for generating release builds, but is not suitable as a build command for day-to-day dvid development.  We need to write a  "developer mode" build script (or adapt the old `CMakeLists.txt` to use a conda environment).~ **Edit:** I added a `Makefile`.

---
This change is [Reviewable](https://reviewable.io/reviews/janelia-flyem/dvid/239)

### CODE REVIEW

**Comment by stuarteberg** [comment]
I've made significant improvements to this PR.  Let's discuss this tomorrow.  In the meantime, you can read the new instructions in the [README][1].

[1]: https://github.com/stuarteberg/dvid/blob/conda-recipe/README.md#installation

**Comment by stuarteberg** [comment]
This PR is ready to go.  Please merge unless you see any major issues.  (I'd like to build a release for Dalhousie, probably tomorrow.)

1. I rebased it on the latest master branch.

2. I added the `kafka` dependency.

3. I moved the install instructions and developer guide to `GUIDE.md`, which also links to the DVID wiki (for now).

4. I implemented `scripts/make-release-distribution.sh`

    The resulting distribution is a `.tar.bz2` file, which contains the complete dvid distribution (including `dvid-web-console`), along with a `README` and example `simple-config.toml`.

    i. Unlike the older dvid distributions, we no longer require `launch_dvid` scripts.
    ii. Furthermore `simple-config.toml` can be used immediately, with no need for user edits.  Just unpack the tarball and run `./bin/dvid serve simple-config.toml`.

**Comment by stuarteberg** [comment]
One last note: Our new conda recipe requires a very recent version of conda-build.  Please use this command to update it:

```
conda update --override-channels -c defaults conda-build
```

**Comment by DocSavage** [comment]
Looks good.  Thanks.

**Pull request merged**
