### PR TITLE
releases file lock if timeout is reached in gbucket driver

### PR DESCRIPTION
**Pull request by stephenplaza**
This change is [Reviewable](https://reviewable.io/reviews/janelia-flyem/dvid/246)

### CODE REVIEW

**Comment by DocSavage** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/gbucket/gbucket.go, line 1759 at r1](https://reviewable.io:443/reviews/janelia-flyem/dvid/246#-L6jOxT7foBPpA2v6uyU:-L6jOxT7foBPpA2v6uyV:bqjadg4) ([raw file](https://github.com/janelia-flyem/dvid/blob/a4269e45e7de410181b8b0f5edb01ccbc734eaaf/storage/gbucket/gbucket.go#L1759)):*
> ```Go
> 	var conditions api.Conditions
> 	conditions.DoesNotExist = true
>         obj_handle := obj_handle_orig.If(conditions)
> ```

It looks like your editor or IDE is not correctly indenting to Go standards.  Could you reformat (e.g., use gofmt command) and resubmit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/janelia-flyem/dvid/246)*

**Comment by stephenplaza** [comment]
I fixed the formatting

**Comment by DocSavage** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/gbucket/gbucket.go, line 1783 at r2](https://reviewable.io:443/reviews/janelia-flyem/dvid/246#-L6lmCzhwY9W5Yjkc5NZ:-L6lmCzhwY9W5Yjkc5N_:bjl9d42) ([raw file](https://github.com/janelia-flyem/dvid/blob/5587c7013dc8d087955c25933f91130f66bef261/storage/gbucket/gbucket.go#L1783)):*
> ```Go
> 			lockheldtime := time.Since(locktime).Seconds()
> 			if lockheldtime > timelimit {
> 				db.UnlockKey(k)
> ```

Seems like this needs to make sure it's a conditional delete.  Could be a race condition between one server just deleting/writing new lock while this server has passed the generation id check and plans on deleting the lock object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/janelia-flyem/dvid/246)*

**Comment by stephenplaza** [comment]
I eliminated the potential for race conditions on delete by making sure that which is deleted is guaranteed to be an old file.

**Pull request merged**
